name: finance_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  dio: any
  intl: ^0.17.0
  get_storage: any
  graphql_flutter: ^5.0.0
  styled_widget: 0.4.0+3
  flutter_easyloading: 3.0.3
  flutter: 
    sdk: flutter
  flutter_icons: 
    git: 
      url: git://github.com/jibiel/flutter-icons.git
      ref: master

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/splash/
    - assets/img/icons/
    - assets/img/backgrounds/
  uses-material-design: true

